### ISSUE TITLE
Documentation suggestion: explanation of threads in Javascript context

### ISSUE THREAD

**Issue by roschler** [tau-prolog/manual#2]
I searched through the documentation and so far I could not find any text that gives an overview on what Tau-Prolog threads  are.  I'm not looking for an extensive technical discussion, just something that differentiates what they are from the normal definition of threads.  Given that the Javascript interpreter is single threaded, I assume that that Tau-Prolog threads are a custom construct whose execution scheduling is controlled by Tau-Prolog itself?

I hope you can see my confusion here given that the Javascript interpreter is single-threaded.  For veteran developers, threads in the classic sense are an execution resource that is scheduled at the O/S level via task switching.  

Note, a short example that shows a simple use case for Tau-Prolog threads would be wonderful.  Threads seem to be a very useful feature that I would like to understand.

**Comment by jariazavalverde** [comment]
Basically, threads allow you to execute multiple goals in the same session. (Note that Tau Prolog can execute asynchronous predicates). For example, DOM events are handled by new threads of the session linking the event.

http://tau-prolog.org/documentation/prolog/dom/bind/4
```javascript
var thread2 = new pl.type.Thread( thread.session ); // <- a new thread is created
var eventObject = new pl.type.DOMEvent( type.id );
var links = {};
if( pl.type.is_variable( event ) )
	links[event.id] = eventObject;
var subs = new pl.type.Substitution( links );
var handler = function( e ) {
	eventObject.event = e;
	thread2.add_goal( goal.apply( subs ) );
	thread2.answer( thread.__calls[0] ); // <- handler looks for answers in the new thread
};
```

In this way, the main thread can continue working with the original goal, and events are handled in separate threads. Sessions contain common information such as the program, the operator table, etc. On the other hand, threads contain, among other things, the stack of choice points.

I hope this short explanation helps you. I'll document it better when I have time. Thanks for the suggestion!

**Comment by roschler** [comment]
@jariazavalverde Thanks!  Just to be absolutely sure, so despite the name, threads in Tau-Prolog are what other Prologs might term _concurrent goals_ and are definitely not separate O/S level threads?  So the entire Tau-Prolog system still runs on a single thread right?

**Comment by jariazavalverde** [comment]
> 
> 
> @jariazavalverde Thanks! Just to be absolutely sure, so despite the name, threads in Tau-Prolog are what other Prologs might term _concurrent goals_ and are definitely not separate O/S level threads? So the entire Tau-Prolog system still runs on a single thread right?

Yes, it runs on a single thread.

**Comment by roschler** [comment]
Thanks again @jariazavalverde.
