### ISSUE TITLE
Typo found in built-in predicates page

### ISSUE THREAD

**Issue by roschler** [tau-prolog/manual#3]
On this page:

http://tau-prolog.org/documentation#builtin

Look for "descomposition".  Change it to "decomposition".

`=../2 – Check the descomposition of a term.`

Suggested additional text:

_This is known as the "univ" operator in Prolog._

That way the reader can search the web for additional information on the operator, which will be very hard to do using the the text "=.." as a search term.

**Comment by jariazavalverde** [comment]
Done! Thanks for your suggestion.
