### ISSUE TITLE
JavaScript linter frowns upon var, suggests let or const

### ISSUE THREAD

**Issue by ghost** [tau-prolog/manual#5]
Was just having a look at:
http://tau-prolog.org/manual/compatibility-with-nodejs

And the example snippet:
```
var pl = require("tau-prolog");
```
But my JavaScript linter from IntelliJ says I should use let or const.

**Comment by jariazavalverde** [comment]
Fixed! Thanks for your suggestion.

**Comment by ghost** [comment]
Disclaimer: I am new to JavaScript, cant give much background information.

Interestingly this one also worked for me, in a node.js enviroment:
```
import pl from "tau-prolog";
```
require gave me an undefined error message, i.e. the function require itself undefined

**Comment by jariazavalverde** [comment]
https://nodejs.org/en/knowledge/getting-started/what-is-require/

Could you show me an example script and the error it gives you?

**Comment by ghost** [comment]
Was using node.js version 14.17.0.
I got this error and used this workaround:
https://learn.coderslang.com/0021-nodejs-require-is-not-defined-error/

Another workaround is:
```
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
```
Which makes require available again.
