### ISSUE TITLE
broken link in http://tau-prolog.org/manual/a-simple-tutorial

### ISSUE THREAD

**Issue by josd** [tau-prolog/manual#7]
The link [ISO Prolog: A Summary of the Draft Proposed Standard](http://fsl.cs.illinois.edu/images/9/9c/PrologStandard.pdf) in http://tau-prolog.org/manual/a-simple-tutorial seems to be broken.

**Comment by jariazavalverde** [comment]
Thanks. Unfortunately, I haven't been able to find the PDF. So I removed the reference.

**Comment by josd** [comment]
True and I am simply using https://en.wikipedia.org/wiki/Prolog#ISO_Prolog in https://github.com/josd/eyebrow
